global:
  storageClass: ebs-gp3 # The name should match to the deployed storageClass. 

architecture: replicaset

auth:
  enabled: true

replicaCount: 2

systemLogVerbosity: 3

persistence:
  enabled: true