apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: crm-secret
data: 
  # mongodb://root:<some-mongodb-root-password>@mongo-mongodb-0.mongo-mongodb-headless.default.svc.cluster.local:27017,mongo-mongodb-1.mongo-mongodb-headless.default.svc.cluster.local:27017,mongo-mongodb-2.mongo-mongodb-headless.default.svc.cluster.local:27017
  MONGODB_URI: bW9uZ29kYjovL3Jvb3Q6PHNvbWUtbW9uZ29kYi1yb290LXBhc3N3b3JkPkBtb25nby1tb25nb2RiLTAubW9uZ28tbW9uZ29kYi1oZWFkbGVzcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3LG1vbmdvLW1vbmdvZGItMS5tb25nby1tb25nb2RiLWhlYWRsZXNzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcsbW9uZ28tbW9uZ29kYi0yLm1vbmdvLW1vbmdvZGItaGVhZGxlc3MuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNwo=